### ISSUE TITLE
capture POST request body in Application Insights

### ISSUE THREAD

**Issue by saravp123** [kentcb/azure_application_insights#36]
Is it possible to capture POST request body in Application Insights as a custom dimension similar to C# code given in solution for https://stackoverflow.com/questions/42686363/view-post-request-body-in-application-insights ?

If so, can anyone help with similar code for dart as I am unable to find ITelemetryInitializer in flutter / dart?

**Comment by kentcb** [comment]
Not really in the scope of this project since it would be potentially costly to do so, but basically I think you'd just want to use `TelemetryHttpClient` as a reference and in the `send` method you can check whether `request` is of type `Request` to get access to the [`body`](https://pub.dev/documentation/http/latest/http/Request/body.html)
